CREATE DATABASE yeticave
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE yeticave;

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name CHAR(255) NOT NULL,
  UNIQUE INDEX (name)
);

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email CHAR(255) BINARY NOT NULL,
  name  CHAR(255) NOT NULL,
  password CHAR(64) NOT NULL,
  avatar_path CHAR(255),
  contacts TEXT NOT NULL,
  UNIQUE INDEX (email)
);

CREATE TABLE lots (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name CHAR(255) BINARY NOT NULL,
  description TEXT NOT NULL,
  img_path CHAR(255),
  price INT UNSIGNED NOT NULL,
  expiration TIMESTAMP NOT NULL,
  price_step INT UNSIGNED NOT NULL,
  category_id INT,  
  author_id INT,
  winner_id INT,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE ON UPDATE CASCADE,  
  FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (winner_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  INDEX (name),
  INDEX (expiration),
  INDEX (author_id)
);

CREATE TABLE bets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sum INT UNSIGNED NOT NULL,
  user_id INT,
  lot_id INT,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (lot_id) REFERENCES lots(id) ON DELETE CASCADE ON UPDATE CASCADE,
  INDEX (lot_id),
  INDEX (user_id)
);
